### ISSUE TITLE
[Feature Request] Support Github Actions

### ISSUE THREAD

**Issue by fjcaetano** [ccmenu/ccmenu#109]
Considering Github Actions are publicly available now, it'd be interesting to support it.

**Comment by paulz** [comment]
Please add support for GitHub Actions, thank you!

**Comment by egpbos** [comment]
Do you see any available options for including this support? Does Actions have any suitable API for this?

**Comment by paulz** [comment]
There are couple of GitHub API: [statuses](https://developer.github.com/v3/repos/statuses/) and [checks](https://developer.github.com/v3/checks/).

Another available option is to use badge svg, which is essentially XML file:
For example our project badge:

https://github.com/sparta-science/connect/workflows/self-hosted-test/badge.svg

is in a text format looks like:
```
<tspan x="4" y="14">passing</tspan>
```
which contains status, in this case: `passing`
or could be failing, running, etc

**Comment by erikdoe** [comment]
There have been several requests over the years to support CI systems that don't provide their build status in _cctray_ format. At the same time, CCMenu is written around this format and it would take some effort to support other APIs.

My argument is that I'd rather see the organisations and teams behind the CI systems put in the effort to provide their build status in _cctray_ format, which has been a documented, simple-to-implement de-facto standard for almost 20 years. That way other tools that understand the _cctray_ format would benefit, too. And, to be honest, I'm looking after CCMenu in my spare time and I'm not super excited about spending time to write code to consume a number of similar but subtlely different APIs. Sometimes this isn't even an option because there might not be publicly accessible test system. And, last but not least, based on my experience, these APIs tend to change and when that happens I'd have a bunch of unhappy users who'd want me to implement the required changes in a timely manner, which is something I can't promise.

I guess the way forward (other than lobbying the teams behind the CI systems to support the _cctray_ format) is to make CCMenu more modular so it becomes  easy for outside contributers to create plug-ins for different APIs. Not sure how feasible that would be with the existing codebase, and how many people would really provide plug-ins for other CI servers.

**Comment by ahvigil** [comment]
there is a feature request with github to support cctray formatted statuses
https://github.community/t/feature-request-publish-workflow-status-in-cctray-format-xml/16815

**Comment by ospfranco** [comment]
For those of you wanting a modern tool that does not rely on the CCTray protocol, you can try an app I created inspired by CCMenu

https://apps.apple.com/de/app/ci-demon/id1560355863?mt=12

**Comment by erikdoe** [comment]
This is now supported in the new version of CCMenu, which is currently released via the App Store.

**Comment by ospfranco** [comment]
Awesome! Thanks a lot!
